# Generated by Django 4.1.7 on 2023-02-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignObject(from_fields=('author_name',), on_delete=django.db.models.deletion.CASCADE, to='forum.user', to_fields=('name',)),
        ),
    ]
